site_name: 足球机器人基地视觉组简介
nav:
    - 首页: index.md
    - 视觉组简介: about-vision-team.md
    - 关于计算机视觉: about-vision.md
    - OpenCV: 
        - OpenCV 介绍: opencv/opencv-introduction.md
        - OpenCV 配置教程: opencv/opencv-configuration.md
    - 传统视觉:
        - 滤波算法: traditional-vision/blur-algorithm.md
        - 边缘检测: traditional-vision/edge-detection.md
        - 霍夫变换: traditional-vision/hoff-transform.md
        - 特征点检测: traditional-vision/feature-point-detection.md
        - 特征点匹配: traditional-vision/feature-point-matching.md
        - 直方图与模板匹配: traditional-vision/histogram-template-match.md
        - 图像金字塔: traditional-vision/image-pyramid.md
    - 相机与视图几何:
        - 相机成像原理: camera-geometry/imageing-principle.md
        - 图像变换: camera-geometry/image-transformation.md
        - 多视图几何: camera-geometry/multi-view-geometry.md
        - 相机标定: camera-geometry/camera-calibration.md
        - 视觉里程计: camera-geometry/vio.md
    - 计算机视觉中的深度学习:
        - 基础知识: deep-learning/base-knowledge.md
        - 前馈神经网络: deep-learning/feedforward-neural-network.md
        - 卷积神经网络: deep-learning/cnn.md
        - 深度学习近况及展望: deep-learning/deep-learning-introduction.md
theme: 
    name: material
    features: 
        - navigation.sections
